# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ef25899c1802cb667ba9da1bbfd0b257a7e29aaff662b9da3503a378db3dcb81cac5bc95c7611d2c26b96a216050bb96c0c592ea9133e6ecd23e88c07dc021d

test:
  secret_key_base: e632f870d0abe6b9ac8ef09fb65f6101777bceb18e404e9be750ec3afc1d5643f797f14958d309f4aa276af6a019981c1fb3807c58354c672e036d81ad5f86d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
